### ISSUE TITLE
What versions of Python do we support?

### ISSUE THREAD

**Issue by cclauss** [MartinPacker/filterCSV#11]
https://devguide.python.org/#status-of-python-branches My preference would be Python 3.6, 3.7 and 3.8 unless you run on some system that still requires Python 3.5 (which EOLs in September).

**Comment by MartinPacker** [comment]
I don't think Mac (especially Catalina) requires 3.5.

**Comment by MartinPacker** [comment]
I'm on 3.6, it would appear.
