### ISSUE TITLE
Add statistics for each level

### ISSUE THREAD

**Issue by MartinPacker** [MartinPacker/filterCSV#14]
(Possibly on the way to a layout engine) I want number of nodes at each level and the number of distinct values at each level.

Possible syntax:

`stats html`

and

`stats text`

and

`stats markdown` - though here the support for tables in Markdown is a little murky so would impose my own taste.

Will create a stats branch to work on this.

**Comment by MartinPacker** [comment]
Maybe also `stats csv`.

**Comment by cclauss** [comment]
I do not understand the usecase.  What would you do with this information?

**Comment by MartinPacker** [comment]
So I could easily say "45 CICS regions attaching to 8 db2 subsystems on 5 systems" - as 45 level 2, 8 level 1, 5 level 0 nodes.

Also counting nodes at each level makes it possible to layout - in SVG or HTML5 Canvas - with the maximum level node count (in this example 45) conditioning the spacing. Naïve layout but something for those who don't have eg iThoughts. BTW the HTML export sort of does this - but clunkily.

**Comment by MartinPacker** [comment]
CSV done. And the difficult part is collating the statistics.

**Comment by cclauss** [comment]
My sense would be that it should be done by traversing the tree.

**Comment by MartinPacker** [comment]
It's done. :-) And now so is HTML table output. Hopefully will pass the test this time - tabs versus spaces.

**Comment by MartinPacker** [comment]
Markdown Tables done. (According to Marked 2 this is the right syntax.)

**Comment by MartinPacker** [comment]
Likewise text output. Will now do README.md and then merge.

**Comment by cclauss** [comment]
I just submitted a minor change to README.md

**Comment by MartinPacker** [comment]
Ah. I wonder what that did to my attempt to merge your pull request.
