### ISSUE TITLE
Add vspread and hspread

### ISSUE THREAD

**Issue by MartinPacker** [MartinPacker/filterCSV#25]
Vertical spread by some number of units - `vspread nnn`

Horizontal spread - `hspread nnn`

**Comment by cclauss** [comment]
Are nnn percentages like (0, 0) would be topLeft and (100, 100) would be bottom right?

**Comment by MartinPacker** [comment]
Actually nnn are arbitrary units - defined by iThoughts. They might be pixels. In the CSV file a horizontal position of 100 looks like "{100,0}" in the "position" column. Likewise vertical position of 100 looks like "{0,100}".

Spread would start at {0,0} and increment across the level 0 nodes. I can see a second level being worthwhile eventually.

**Comment by MartinPacker** [comment]
Done.
