### ISSUE TITLE
Trim unnecessary level columns on output

### ISSUE THREAD

**Issue by MartinPacker** [MartinPacker/filterCSV#26]
Right now all 21 column headings are written out, even though many fewer are needed. A nit but it looks stupid.

**Comment by MartinPacker** [comment]
Design would be to use the method CSVTree.calculateMaximumLevel to determine how any levels are needed in the heading line.

**Comment by cclauss** [comment]
> all 21 column headings are written out

In which output file formats?

**Comment by MartinPacker** [comment]
This is CSV - using CSVWriter built-in class. So trimming the internal representation is probably the thing to do - before invoking CSVWriter.write.

**Comment by MartinPacker** [comment]
I just did this. Will land with importxml branch.
