### ISSUE TITLE
Need // at start of line to signal comment

### ISSUE THREAD

**Issue by MartinPacker** [MartinPacker/filterCSV#33]
Commenting out eg "ABCD nc" would be nice:

`// ABCD nc \\`

Which would require us to deviate from the 2 parms per action. So NOT a starter bug.

**Comment by cclauss** [comment]
Which file format are we talking about? .csv?   What about # instead?

**Comment by MartinPacker** [comment]
I'm talking about the command line input. There doesn't seem to be a way in bash to comment out a line.

**Comment by cclauss** [comment]
# is a comment in sh, bash, csh, zsh , etc.

**Comment by MartinPacker** [comment]
But not in the middle of something like this:

    #!/usr/bin/env bash
    filterCSV \
    all FFFFFF \
    stats markdown \
    10.220.60. nc \
    10.220.61. nc \
    10.227.13. nc \
    107.216.33. nc \
    10.227.16. nc \
    10.227.244. nc \
    180.14.229. nc \
    < DDFTOPDI.csv \
    > fixed-DDFTOPDI.csv

The idea is to be able to effectively comment out any of the lines in the middle.

**Comment by cclauss** [comment]
https://superuser.com/questions/508507/linux-bash-script-single-command-but-multiple-lines last one or... https://superuser.com/questions/238791/comments-in-a-multi-line-bash-command

**Comment by MartinPacker** [comment]
Implemented as `//` in v1.9.
