### ISSUE TITLE
Merge as bullets under parent

### ISSUE THREAD

**Issue by MartinPacker** [MartinPacker/filterCSV#45]
It would be useful to allow promote to actually merge as bullets under parent. (iThoughts CSV node values can be Markdown.)

**Comment by cclauss** [comment]
Can you please provide an example of what this would look like?

**Comment by MartinPacker** [comment]
Would look like a single node:
---
myElement
* x='123'
* y='456'
-----
in the "XML attribute merge" case. (Down from 3 nodes: "myElement", "x=", "y="

**Comment by MartinPacker** [comment]
To do this for a node requires the following steps:

1. Get the node's text i.e. "cell" value.
2. Get the node's parent.
3. Append the node's text as a bullet to the parent's text - with appropriate Markdown syntax.
4. Promote the node's children to be children of the node's parent, at the point this node is.
5. Delete the node.

This would be repeated for each selected node, their parent node and their children.

Thinking of the syntax to be <match> asbullet

A similar thing could be done for numbered list bullets, though the Markdown is slightly different.

Some of the code replicates what's in CSVTree.promoteLevel - so some abstraction might be possible/desirable.

**Comment by MartinPacker** [comment]
Implemented in 1.3.
