### ISSUE TITLE
Functions should return text instead of printing

### ISSUE THREAD

**Issue by cclauss** [MartinPacker/filterCSV#5]
Functions that return the [output formats](https://github.com/MartinPacker/filterCSV#output-formats) should return reformatted text instead of printing directly.  This will allow us to test those functions with different inputs and verify that the outputs match our expectations.  This will also give us flexibility to write each function's output to multiple locations.  If functions find errors in the input data, they should raise exceptions (ValueError, etc.) so our tests can cover some garbage-in scenarios.

**Comment by MartinPacker** [comment]
Done and merged. Was "print" branch.
