### ISSUE TITLE
Add Graphviz .dot output format

### ISSUE THREAD

**Issue by MartinPacker** [MartinPacker/filterCSV#53]
This is a simple text-based format that can be turned very easily into a directed graph in a variety of formats, e.g. PNG. You use the dot command in the Graphviz package to do this:

`dot -T png test.dot > test.png`

**Comment by cclauss** [comment]
https://github.com/mingrammer/diagrams

**Comment by MartinPacker** [comment]
Shipped in 1.4 on 27 June 2020. Closed
